services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsLuceneBundle\Normalizer\DocumentKeyValueNormalizer:
        tags:
            - { name: dynamic_search.document_normalizer, identifier: lucene_document_key_value_normalizer, index_provider: lucene }