services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Output Channel Services

    DsLuceneBundle\OutputChannel\AutoCompleteOutputChannel:
        tags:
            - { name: dynamic_search.output_channel, identifier: lucene_autocomplete }

    DsLuceneBundle\OutputChannel\SuggestionsOutputChannel:
        tags:
            - { name: dynamic_search.output_channel, identifier: lucene_suggestions }

    DsLuceneBundle\OutputChannel\SearchOutputChannel:
        tags:
            - { name: dynamic_search.output_channel, identifier: lucene_search }

    DsLuceneBundle\OutputChannel\MultiSearchOutputChannel:
        tags:
            - { name: dynamic_search.output_channel, identifier: lucene_multi_search }


    # Filter / Action

    DsLuceneBundle\OutputChannel\Modifier\Filter\QueryCleanTermFilter:
        tags:
            - { name: dynamic_search.output_channel.modifier.filter, output_channel_service_identifier: lucene_autocomplete, filter: query.clean_term }
            - { name: dynamic_search.output_channel.modifier.filter, output_channel_service_identifier: lucene_suggestions, filter: query.clean_term }
            - { name: dynamic_search.output_channel.modifier.filter, output_channel_service_identifier: lucene_search, filter: query.clean_term }

    DsLuceneBundle\OutputChannel\Modifier\Filter\QueryTermBuildFilter:
        tags:
            - { name: dynamic_search.output_channel.modifier.filter, output_channel_service_identifier: lucene_suggestions, filter: query.build_term }
            - { name: dynamic_search.output_channel.modifier.filter, output_channel_service_identifier: lucene_search, filter: query.build_term }