imports:
    - { resource: services/*.yml }

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsLuceneBundle\Service\LuceneStorageBuilder:
        arguments:
            $basePath: '%dynamic_search.ds_lucene.index.base_path%'